Unit Test for Programming Assignment 2
========================================================

This is the documentation for the test cases for Programming Assignment 2.

Source Code
-----------
```{r}
## define cacheSolve() and makeCacheMatrix() functions
source("cachematrix.r",echo=TRUE)
```

Test Case 1
-----------
This test case shows the calculation of the matrix inverse

```{r}
## define test case matrix
mat <- makeCacheMatrix(matrix(1:4,ncol=2))

## return matrix
mat$get()

## retrieve matrix inverse
## should not indicate getting value from cache
cacheSolve(mat)

## retrieve matrix inverse again
## should see message that marix is from cache
cacheSolve(mat)


## multiple the matrix with its inverse
## this results in the identity matrix
mat$get() %*% cacheSolve(mat)
```


Test Case 2
-----------
This test case will show timing differences for large matrix

```{r}
## define large n-by-n square matrix
set.seed(1)
n <- 2500
mat <- makeCacheMatrix(matrix(sample(n^2),ncol=n))

## first-time retrieval of inverse
system.time(m1 <- cacheSolve(mat))

## second-time retrieval of inverse should be faster
## elapsed time should be less than the first-time retrieval
system.time(m2 <- cacheSolve(mat))

## Test if first and second retrievals are the same
## this should return TRUE
identical(m1,m2)

```

